### ISSUE TITLE
Addition of UI

### ISSUE THREAD

**Issue by nihalawasthi** [Lakshya1726/CRYPTOANALYSIS#25]
| name     | about                                         | title | labels   | assignees |
|----------|-----------------------------------------------|-------|----------|-----------|
| CLI & GUI | Create Command Line and Graphical User Interfaces for the project | UI    | Addition |           |

### **Feature Description**
This feature aims to develop both Command-Line Interface (CLI) and Graphical User Interface (GUI) for the project. The CLI will provide a command line-based interface for admins, advanced users to interact with the project, while the GUI will offer a visual interface, making it easier for non-technical users to navigate and operate the project functionalities.

### **What problem does this feature solve?**
- **Accessibility**: Provides two options for interaction, allowing both technical and non-technical users to engage with the project. The CLI allows for quicker input by experienced users, while the GUI makes the application more accessible to users who may not be familiar with command-line tools.
- **User Experience**: Enhances the overall user experience by providing an intuitive GUI for ease of use and a CLI for detailed control and automation.
- **Flexibility**: Adds flexibility for users who prefer different interaction methods depending on their environment or preferences.

### **Additional Context**
- CLI will include features such as custom commands, error handling, and support for batch processing.
- GUI will be developed using a framework like Electron or PyQt, depending on the project’s needs. It will feature clear navigation, responsive design, and error handling similar to the CLI.

---

| UI Type | Purpose                                           | Framework/Tools                 |
|---------|---------------------------------------------------|----------------------------------|
| CLI     | Provide command-based interaction for advanced users | Bash, Python    |
| GUI     | Simplified visual interaction for non-technical users | Electron, PyQt, Tkinter          |

**Comment by NareenAsad** [comment]
can I work on it

**Comment by nihalawasthi** [comment]
> can I work on it

@NareenAsad  if you want to contribute to a project you have to create a issue and then wait for approval from Author
the project will be assigned to whoever created the issue
